---

dist: trusty
sudo: false
language: python

branches:
  only:
    - qa/0.x
    - /^stable\/\d+\.\d+\.x$/

addons:
  apt:
    packages:
      - python-pip
      - p7zip-full
      - unar

cache:
  - pip

before_install:
  - pip install tox

install: true

before_script:
  # Needed by test_duracloud.py
  - sudo mkdir -p /var/archivematica/storage_service
  - sudo chown -R $USER /var/archivematica/storage_service

script: tox

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=linting
    - python: "3.6"
      env: TOXENV=checkformigrations
  allow_failures:
    - python: "3.6"
      env: TOXENV=py36
