version: "3"

services:

  archivematica-storage-service:
    build:
      context: "../"
      dockerfile: "Dockerfile"
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-}
    entrypoint: ""
    working_dir: "/src"
    command: ["./integration/wait-for-it.sh", "mysql:3306", "--timeout=30", "--", "pytest", "storage_service", "integration"]
    environment:
      PYTEST_ADDOPTS: ${PYTEST_ADDOPTS:-}
      FORWARDED_ALLOW_IPS: "*"
      SS_GUNICORN_ACCESSLOG: "/dev/null"
      DJANGO_SETTINGS_MODULE: "storage_service.settings.testmysql"
      SS_GNUPG_HOME_PATH: "/var/archivematica/storage_service/.gnupg"
    volumes:
      - "../:/src"
    links:
      - "minio"
      - "mysql"

  minio:
    image: "minio/minio:RELEASE.2020-05-08T02-40-49Z"
    command: "server /data"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
      MINIO_REGION_NAME: "planet-earth"
      MINIO_BROWSER: "off"
    expose:
      - "9000"

  mysql:
    image: "percona:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # These are used in the storage_service.settings.testmysql module
      MYSQL_USER: "archivematica"
      MYSQL_PASSWORD: "demo"
